### ISSUE TITLE
css 中使用 flex 的小技巧

### ISSUE THREAD

**Issue by Yangjia23** [Yangjia23/recode-work-trouble#2]
**1.最后一个子元素靠右排列** 

> `margin-left` 巧用

当子元素的就 2 个时，可直接设置父级
 ```html
<div class="box">
	<div class="item-1">111</div>
	<div class="item-2">222</div>
</div>
```
```css
.box{
	display: flex;
	justify-content: space-between;
	width: 200px;
	border: 1px solid red;
}
```
当子元素数量超过 2 个时，要求最后一个子元素靠右排列，可设置
 ```html
<div class="box">
	<div class="item-1">111</div>
	<div class="item-2">222</div>
        <div class="item-3">333</div>
</div>
```
```css
.box {
   display: flex;
   width: 200px;
   border: 1px solid red;
}

.item-3{
    margin-left: auto;
}
```
